#!/bin/sh
#
# Copyright (C) 2004-2023 Francesco P. Lovergine <frankie@debian.org>
#
# This script is useful on Debian GNU/Linux as an alternative to autoreconf.
# Adaptable to other platforms mutata mutanda.
#

if [ $(command -v autoreconf|wc -l) -eq 1 ]
then
    autoreconf --verbose --force --install
else
    autoheader \
    && aclocal \
    && autoconf \
    && automake --add-missing --force --copy 
fi
